# Generated by Django 5.2.6 on 2025-10-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_staff_full_name_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
