# Generated by Django 5.2.6 on 2025-10-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Staff',
        ),
        migrations.AddField(
            model_name='task',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.staff'),
            preserve_default=False,
        ),
    ]
