# Generated by Django 5.2.6 on 2025-10-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_task_staff_task_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='Staff',
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.staff'),
            preserve_default=False,
        ),
    ]
